{
 "title": "Plataforma de Reservas - V3",
 "tags": [
  "reservas",
  "incus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": " Peticiones Reales (Usuarios)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_total{endpoint!=\"/metrics\", job=\"app-backend\"}) or vector(0)"
    }
   ]
  },
  {
   "title": " Peticiones Internas (/metrics)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_requests_total{endpoint=\"/metrics\", job=\"app-backend\"}) or vector(0)"
    }
   ]
  },
  {
   "title": " Tráfico Real de Usuarios por Endpoint (Req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum by (endpoint, method) (rate(http_requests_total{endpoint!=\"/metrics\", job=\"app-backend\"}[1m]))"
    }
   ]
  }
 ]
}